<a href="https://colab.research.google.com/github/nurskurmanbekov/Applied-Data-Science-with-Python/blob/main/Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b>Course Outline</b>



1.   Prerequest  Python Knowledge 
2.   The pandas Toolkit 
3.   Advanced Querying and Manipulation with pandas 
4.   Basic Statistical  Analysis  with numpy  and scipy,  and project


In this Scpecalization also in 1'st course we will use Jupyter Notebook.



# ***Function***

In [95]:
x = 1 
y = 2
x + y 

3

In [96]:
x 

1

In [97]:
def add_numbers(x, y):
  return x + y

add_numbers(1,2)

3

In [98]:
def add_numbers(x, y, z = None):
  if (z == None):
    return x + y
  else:
    return x + y + z
print(add_numbers(1,2,4))
print(add_numbers(1,2))

7
3


In [99]:
def add_numbers(x, y, z = None, flag = False):
  if (flag):
    print('Flag is True!')
  if (z == None):
    return x + y
  else:
    return x + y + z
print(add_numbers(1,2, flag = True))
print(add_numbers(1,2,3, flag = False)) 
print(add_numbers(1,2, flag = False))

Flag is True!
3
6
3


This function should add the two values if the value of the "kind" parameter is "add" or is not passed in, otherwise it should subtract the second value from the first. 

Can you fix the function so that it works?



```
 def do_math(?, ?, ?):
  if (kind=='add'):
    return a+b
  else:
    return a-b

do_math(1, 2)
```



In [100]:
def do_math(a, b, kind='add'):
    if (kind=='add'):
        return a+b
    else:
        return a-b

do_math(1, 2)

3

# ***Python Types and Sequences***


In [101]:
type('This is string')

str

In [102]:
type(None)

NoneType

In [103]:
type(1.0)

float

In [104]:
type(add_numbers)

function

In [105]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [106]:
x = [1, 'a', 2, 'b']
type(x)

list

In [107]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [108]:
for item  in x:
  print(item)

1
a
2
b
3.3


In [109]:
i = 0
while(i != len(x) ):
  print(x[i])
  i = i + 1

1
a
2
b
3.3


In [110]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [111]:
[1] + [3]

[1, 3]

In [112]:
[1] * 3

[1, 1, 1]

In [113]:
1 in [1,2,3]

True

In [114]:
x = 'This is a string'
print(type(x))

<class 'str'>


In [115]:
print(x[0])
print(x[0:1])
print(x[0:2])
print(x[0:3])
print(x[0:4])
print(x[0:5])
print(x[0:6])
print(x[0:7])
print(x[0:8])

T
T
Th
Thi
This
This 
This i
This is
This is 


In [116]:
print(x[0:1])

T


In [117]:
i = 0
while (i != len(x)+1):
  print(x[0:i])
  i= i+1


T
Th
Thi
This
This 
This i
This is
This is 
This is a
This is a 
This is a s
This is a st
This is a str
This is a stri
This is a strin
This is a string


In [118]:
x[-1]

'g'

In [119]:
x[-4:-2]

'ri'

In [120]:
x[:3]

'Thi'

In [121]:
x[3:]

's is a string'

What would be an appropriate slice to get the name "Christopher" from the string "Dr. Christopher Brooks"?



```
x = 'Dr. Christopher Brooks'

print(x[???])
```



In [122]:
x = 'Dr. Christopher Brooks'

print(x[4:15])

Christopher


In [123]:
firstname = 'Chistopher'
lastname = 'Brooks'
print(firstname + ' ' + lastname)
print(f"{firstname} {lastname}")

Chistopher Brooks
Chistopher Brooks


In [124]:
print(firstname * 3)
print('Chris' in firstname)

ChistopherChistopherChistopher
False


In [125]:
firstname  = 'Chirstopher Arthur Hansen Brooks'.split(' ')[0]
firstname

'Chirstopher'

In [126]:
lastname  = 'Chirstopher Arthur Hansen Brooks'.split(' ')[3]
lastname

'Brooks'

In [127]:
x = {'Christopher Brooks' : 'brooksch@umich.edu', 'Bill Gates' : 'billg@microsoft.com'}
x['Christopher Brooks']

'brooksch@umich.edu'

In [128]:
x['Kevyn  Collins-Thompson'] = None
x['Kevyn  Collins-Thompson'] 

In [129]:
for name in x:
  print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [130]:
for email in x.values():
  print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [131]:
for name, email in x.items():
  print(name)
  print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn  Collins-Thompson
None


In [132]:
for name, email in x.items():
  print(f'{name} {email}\n')


Christopher Brooks brooksch@umich.edu

Bill Gates billg@microsoft.com

Kevyn  Collins-Thompson None



In [133]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [134]:
print(f"{fname} {lname} {email}")

Christopher Brooks brooksch@umich.edu


# ***Python More on Strings***


In [135]:
print('Chris'+ str(2))

Chris2


In [136]:
sales_record = {'price' : 3.24,
                 'num_items' : 4,
                 'person' : 'Chris'}
sales_statement = '{} bought {} item(s) at a price of {} each for a total  of {}'
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items'] * sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total  of 12.96


## ***Python Demonstration: Reading and Writing CSV files***


<b>Data Files and Summary Statistics</b>

In [137]:
#import library
import csv
%precision 2

with open('mpg.csv') as csvfile:
  mpg = list(csv.DictReader(csvfile))

mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [138]:
len(mpg)

234

In [139]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [140]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [141]:
sum(float(d['hwy']) for d in mpg)/ len(mpg)

23.44

In [142]:
cyllinders = set(d['cyl'] for d in mpg)
cyllinders

{'4', '5', '6', '8'}

In [143]:
CtyMpgByCyl = []
for c in cyllinders:
  summpg = 0
  cyltypecount = 0
  for d in mpg:
    if d['cyl'] == c:
      summpg += float(d['cty'])
      cyltypecount += 1
  CtyMpgByCyl.append((c,summpg / cyltypecount))

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [144]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

# ***Python Dates and Times***


In [145]:
import datetime as dt
import time as tm

In [146]:
tm.time()

1656085496.04

In [147]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2022, 6, 24, 15, 44, 56, 58324)

In [148]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2022, 6, 24, 15, 44, 56)

In [149]:
delta = dt.timedelta(days = 100)

In [150]:
today = dt.date.today()

In [151]:
today - delta

datetime.date(2022, 3, 16)

In [152]:
today > today-delta

True

# ***Advanced Python Objects, map()***


In [153]:
class Person:
  departament = 'School of Information'

  def set_name(self, new_name):
    self.name = new_name

  def set_location(self, new_location):
    self.location = new_location

In [154]:
person = Person()
person.set_name('Kurmanbekov Nursultan')
person.set_location('New Your, Wall Stree 001')
print('{} live in {} and works  in the departament {}'.format(person.name, person.location, person.departament))

Kurmanbekov Nursultan live in New Your, Wall Stree 001 and works  in the departament School of Information


In [155]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.00, 12.34, 2.01]
cheapest =  map(min, store1, store2)
cheapest

***Here is a list of faculty teaching this MOOC. Can you write a function and apply it using map() to get a list of all faculty titles and last names (e.g. ['Dr. Brooks', 'Dr. Collins-Thompson', …]) ?***



```
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return #Your answer here

list(map(#Your answer here))

```



In [156]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

# ***Advanced Python Lambda and List Comprehensions***


In [157]:
my_function = lambda a, b, c  : a + b

In [158]:
my_function(1,2,3)

3

***Convert this function into a lambda:***



```
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person:???))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))

```



In [159]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [160]:
my_list = []
for number  in range(0, 1000):
  if number  % 2 == 0:
    my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [161]:
my_list = [number for number in range(0, 1000) if number % 2 == 0 ]

In [162]:
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

***Here, why don’t you try converting a function into a list comprehension.***



```
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [???]
```



In [163]:
 def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j * i for i in range(10) for j in range(10)]

True

In [164]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

# ***Numerical Python Library (NumPy)***


Numpy is the fundamental  package  for numeric computing  with Python. It provides  powerful ways to create, store, and/or manipulate data, which makes  it able  to seamlessly  and  speedily integrate  with  a wide  variety of datebase. This is also the foundation  that Pandas is built  on, which  is a high-perfom data-entric  package that we  will learn  later in the course.

In the lecture, we will talk about array certain  data types, manipulating array, selecting elements from arrays, and loading dataset into array. Such functions  are useful  for manipulating data and understanding  the fucntionalities  of other  common Python data-packages.

In [165]:
import numpy as np
import math 

<b>Array Creation</b>

In [166]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [167]:
print(a.ndim)

1


In [168]:
b = np.array([[1,2,3], [4,5,6]])

In [169]:
print(b.ndim)

2


In [170]:
b.shape

(2, 3)

In [171]:
a.shape

(3,)

In [172]:
print(a.dtype)
print(b.dtype)

int64
int64


In [173]:
c = np.array([2.2, 3.3, 4.4, 5.5])

In [174]:
c.dtype

dtype('float64')

In [176]:
d = np.zeros((2,3))

In [177]:
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [178]:
c = np.ones((4,4))

In [179]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [185]:
np.random.rand(3,3)

array([[0.81, 0.55, 0.14],
       [0.98, 0.6 , 0.82],
       [0.75, 0.65, 0.49]])

In [186]:
f = np.arange(10, 100, 2)

In [187]:
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [189]:
np.linspace(0, 2, 15  )

array([0.  , 0.14, 0.29, 0.43, 0.57, 0.71, 0.86, 1.  , 1.14, 1.29, 1.43,
       1.57, 1.71, 1.86, 2.  ])

<b>Array Operations</b>

In [194]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a - b
print(c)
print('\n')
d = a * b
print(d)

[ 9 18 27 36]


[ 10  40  90 160]


In [195]:
farenheit = np.array([0, -10, -5, -15, 0])
#  Formula is ((*F - 32) * 5/9 = *C)
celcius = ((farenheit - 31) * (5/9))

In [196]:
celcius

array([-17.22, -22.78, -20.  , -25.56, -17.22])

In [198]:
celcius > -20

array([ True, False, False, False,  True])

In [199]:
celcius % 2 == 0

array([False, False,  True, False, False])

In [202]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [203]:
print(A * B)

[[2 0]
 [0 4]]


In [204]:
print(A@B)

[[5 4]
 [3 4]]


In [205]:
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)
